require: rubocop-rspec

Metrics/CyclomaticComplexity:
  Exclude:
  #everything here was hyrax-specific

Metrics/ClassLength:
  Exclude:
  #everything here was hyrax-specific
  - 'app/controllers/catalog_controller.rb'

Metrics/ParameterLists:
  Exclude:
  #everything here was hyrax-specific

Metrics/ModuleLength:
  Exclude:
  #everything here was hyrax-specific

Metrics/MethodLength:
  Exclude:
  #everything here was hyrax-specific

Style/LineEndConcatenation:
  Exclude:
  #everything here was hyrax-specific

Style/PredicateName:
  Exclude:
  #everything here was hyrax-specific

Rails/Output:
  Exclude:
  #keeping this as we may use generators in the future
    - 'lib/generators/**/*'

Rails/HasAndBelongsToMany:
  Exclude:
  #everything here was hyrax-specific

RSpec/NamedSubject:
  Enabled: false

RSpec/ExampleLength:
  Max: 7 
  Exclude:
  #everything here was hyrax-specific

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/AnyInstance:
  Exclude:
  #everything here was hyrax-specific
