language: ruby

rvm:
  - "2.0.0"

notifications:
  email:
    recipients:
      - hortongn@ucmail.uc.edu
      - newmanld@ucmail.uc.edu
      - scherztc@ucmail.uc.edu
      - vanmiljf@ucmail.uc.edu
      - wamsleai@ucmail.uc.edu
      - burkepk@ucmail.uc.edu
    on_success: "change"
    on_failure: "always"

bundler_args: --without headless debug

before_install:
  - gem install bundler
  - sudo apt-get install libclamav-dev libclamav6 clamav clamav-base clamav-daemon clamav-freshclam clamav-unofficial-sigs
  - gem install clamav
  - sudo freshclam  
  
before_script:
  - "cp config/doi.yml.travis config/doi.yml"  
  - "cp config/database.yml.travis config/database.yml"  

script: "bundle exec rake ci"

