language: ruby

rvm:
  - "2.0.0"

script: "rake ci"

bundler_args: --without headless debug

before_install:
  - gem install bundler
  - sudo apt-get install libclamav-dev libclamav6 clamav clamav-base clamav-daemon clamav-freshclam clamav-unofficial-sigs
  - gem install clamav
