language: ruby

rvm:
  - "2.1.6"

notifications:
  email:
    recipients:
      - scholar@uc.edu
    on_success: "change"
    on_failure: "always"

bundler_args: --without headless debug

before_install:
  - gem install bundler
  
before_script:
  - "cp config/database.yml.sample config/database.yml"  
  - "cp config/doi.yml.sample config/doi.yml"  
  - "cp config/fedora.yml.sample config/fedora.yml"  
  - "cp config/solr.yml.sample config/solr.yml"  
  - "cp config/authentication.yml.sample config/authentication.yml"
  - "cp config/initializers/devise.rb.sample config/initializers/devise.rb"
script: "bundle exec rake ci"

notifications:
  slack: uc-libraries-digital:7gc9gvfCKedkWXORxCo5Hndx

