language: ruby
sudo: false

cache:
  bundler: true
  directories:
    - "travis_phantomjs"

before_install:
  - gem install brakeman
  - gem install bundler
  - gem install rubocop -v '0.42.0'
  - gem install rubocop-rspec -v '1.7'
rvm:
  - 2.2.2
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  matrix:
    - "RAILS_VERSION=4.2.7.1"
notifications:
  email:
    recipients:
      - crowesn@ucmail.uc.edu
      - scherztc@ucmail.uc.edu
      - haitzlm@ucmail.uc.edu
script:
  - bundle exec rake ci
services:
  - redis-server
before_script:
  - jdk_switcher use oraclejdk8
  - brakeman
  - rubocop
notifications:
  slack: uc-libraries-digital:7gc9gvfCKedkWXORxCo5Hndx
