language: ruby

rvm:
  - "2.0.0"

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

script: "rake ci"

bundler_args: --without headless

before_install:
  - gem install bundler
  - sudo apt-get install libclamav-dev libclamav6
  - gem install clamav

branches:
  only:
    - master
    - develop
    - sandbox

env:
  matrix:
    - SPEC_GROUP=2
    - SPEC_GROUP=1
    - SPEC_GROUP=0
