development:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://curate-devdb.uc.edu/fedora
test: &TEST  
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= "data.local:#{ENV['TEST_JETTY_PORT'] || 8080}/fedora-test" %>
production:
  user: fedoraAdmin
  password: fedoraAdmin
  url: https://curate-qadb.uc.edu/fedora
cucumber:
  <<: *TEST
ci:
  <<: *TEST
