development:
  user: fedoraAdmin
  password: bamboo_fedora_password
  url: bamboo_fedora_url
test: &TEST  
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= "http://127.0.0.1:#{ENV['TEST_JETTY_PORT'] || 4001}/fedora-test" %>
production:
  user: fedoraAdmin
  password: bamboo_fedora_password
  url: bamboo_fedora_url
cucumber:
  <<: *TEST
ci:
  <<: *TEST
