development:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://curate-devdb.uc.edu/fedora
test: &TEST  
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= "http://127.0.0.1:#{ENV['TEST_JETTY_PORT'] || 4001}/fedora-test" %>
production:
  user: fedoraAdmin
  password: bamboo_fedora_password
  url: https://curate-qadb.uc.edu/fedora
cucumber:
  <<: *TEST
ci:
  <<: *TEST
