development:
  manager_usernames:
  - bamboo_manager_email1
  - bamboo_manager_email2
  - bamboo_manager_email3
  - bamboo_manager_email4
  - bamboo_manager_email5
  - bamboo_manager_email6
  - bamboo_manager_email7
  - bamboo_manager_email8  
test:
  manager_usernames:
  - bamboo_manager_email1
  - bamboo_manager_email2
  - bamboo_manager_email3
  - bamboo_manager_email4
  - bamboo_manager_email5
  - bamboo_manager_email6
  - bamboo_manager_email7
  - bamboo_manager_email8  
production:
  manager_usernames:
  - bamboo_manager_email1
  - bamboo_manager_email2
  - bamboo_manager_email3
  - bamboo_manager_email4
  - bamboo_manager_email5
  - bamboo_manager_email6
  - bamboo_manager_email7
  - bamboo_manager_email8  
