development:
  catalog:
    rows: 10
    qt: search
    qf:
      - desc_metadata__abstract_tesim
      - desc_metadata__advisor_tesim
      - desc_metadata__alternate_title_tesim
      - desc_metadata__college_tesim
      - desc_metadata__committee_member_tesim
      - desc_metadata__contributor_tesim
      - desc_metadata__coverage_spatial_tesim
      - desc_metadata__coverage_temporal_tesim
      - desc_metadata__creator_tesim
      - desc_metadata__date_created_tesim
      - desc_metadata__degree_tesim
      - desc_metadata__department_tesim
      - desc_metadata__description_tesim
      - desc_metadata__genre_tesim
      - desc_metadata__journal_title_tesim
      - desc_metadata__language_teim
      - desc_metadata__language_tesim
      - desc_metadata__note_tesim
      - desc_metadata__note_teim
      - desc_metadata__publisher_tesim
      - desc_metadata__publisher_digital_tesim
      - desc_metadata__rights_tesim
      - desc_metadata__subject_tesim
      - desc_metadata__type_tesim
      - desc_metadata__title_tesim
      - desc_metadata__alternate_phone_number_tesim
      - desc_metadata__blog_tesim
      - desc_metadata__campus_phone_number_tesim
      - desc_metadata__personal_webpage_tesim
      - desc_metadata__first_name_tesim
      - desc_metadata__last_name_tesim
  people:
test:
  catalog:
    rows: 10
    qt: search
    qf:
      - desc_metadata__abstract_tesim
      - desc_metadata__advisor_tesim
      - desc_metadata__alternate_title_tesim
      - desc_metadata__bibliographic_citation_tesim
      - desc_metadata__college_tesim
      - desc_metadata__committee_member_tesim
      - desc_metadata__contributor_tesim
      - desc_metadata__coverage_spatial_tesim
      - desc_metadata__coverage_temporal_tesim
      - desc_metadata__creator_tesim
      - desc_metadata__date_created_tesim
      - desc_metadata__degree_tesim
      - desc_metadata__department_tesim
      - desc_metadata__description_tesim
      - desc_metadata__genre_tesim
      - desc_metadata__journal_title_tesim
      - desc_metadata__language_teim
      - desc_metadata__language_tesim
      - desc_metadata__note_tesim
      - desc_metadata__note_teim
      - desc_metadata__publisher_tesim
      - desc_metadata__publisher_digital_tesim
      - desc_metadata__rights_tesim
      - desc_metadata__subject_tesim
      - desc_metadata__type_tesim
      - desc_metadata__title_tesim
      - desc_metadata__alternate_phone_number_tesim
      - desc_metadata__blog_tesim
      - desc_metadata__campus_phone_number_tesim
      - desc_metadata__personal_webpage_tesim
      - desc_metadata__first_name_tesim
      - desc_metadata__last_name_tesim
  people:
production:
  catalog:
    rows: 10
    qt: search
    qf:
      - desc_metadata__abstract_tesim
      - desc_metadata__advisor_tesim
      - desc_metadata__alternate_title_tesim
      - desc_metadata__bibliographic_citation_tesim
      - desc_metadata__college_tesim
      - desc_metadata__committee_member_tesim
      - desc_metadata__contributor_tesim
      - desc_metadata__coverage_spatial_tesim
      - desc_metadata__coverage_temporal_tesim
      - desc_metadata__creator_tesim
      - desc_metadata__date_created_tesim
      - desc_metadata__degree_tesim
      - desc_metadata__department_tesim
      - desc_metadata__description_tesim
      - desc_metadata__genre_tesim
      - desc_metadata__journal_title_tesim
      - desc_metadata__language_teim
      - desc_metadata__language_tesim
      - desc_metadata__note_tesim
      - desc_metadata__note_teim
      - desc_metadata__publisher_tesim
      - desc_metadata__publisher_digital_tesim
      - desc_metadata__rights_tesim
      - desc_metadata__subject_tesim
      - desc_metadata__type_tesim
      - desc_metadata__title_tesim
      - desc_metadata__alternate_phone_number_tesim
      - desc_metadata__blog_tesim
      - desc_metadata__campus_phone_number_tesim
      - desc_metadata__personal_webpage_tesim
      - desc_metadata__first_name_tesim
      - desc_metadata__last_name_tesim
  people:
