# This is a sample config file that does not have multiple solr instances. You will also need to be sure to
# edit the fedora.yml file to match the solr URL for active-fedora.
development:
  url: http://localhost:4001/solr/development
test: &TEST
  url: <%= "http://127.0.0.1:#{ENV['TEST_JETTY_PORT'] || 4001}/solr/test" %>
cucumber:
  <<: *TEST
ci:
  <<: *TEST
production:
  url: http://your.production.server:8080/bl_solr/core0
